"""empty message

Revision ID: 93cb27c348ff
Revises: 
Create Date: 2020-05-31 14:54:52.011120

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93cb27c348ff'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('website', 'show_admin_panel',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.drop_column('website', 'font_style')
    op.drop_column('website', 'font_size')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('website', sa.Column('font_size', sa.VARCHAR(length=200), nullable=True))
    op.add_column('website', sa.Column('font_style', sa.VARCHAR(length=200), nullable=True))
    op.alter_column('website', 'show_admin_panel',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
