"""empty message

Revision ID: e858e00c8a50
Revises: 
Create Date: 2020-06-08 23:19:39.338935

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e858e00c8a50'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('website_link_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'post', 'website_link', ['website_link_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'post', type_='foreignkey')
    op.drop_column('post', 'website_link_id')
    # ### end Alembic commands ###
